# Generated by Django 4.0.4 on 2022-05-11 18:36

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='profilePics/default.jpg', upload_to='profilePics'),
        ),
    ]
